language: go

go:
  - 1.8
  - master

before_install:
  - psql  -c "CREATE DATABASE gloat_test;" -U postgres
  - mysql -e 'CREATE DATABASE myapp_test;'

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3
  - make test

env:
  global:
    - DATABASE_SRC=testdata/migrations
  matrix:
    - DATABASE_URL='postgres://postgres@localhost/gloat_test?sslmode=disable'
    - DATABASE_URL='mysql://travis@tcp(127.0.0.1:3306)/gloat_test'
    - DATABASE_URL='sqlite3://localhost/:memory:'
